language: python

dist: xenial

cache: pip

python:
    - "3.6"
    - "3.7"

install:
    - pip install -U -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
    - scripts/test

after_script:
    - codecov
